services:
  backend:
    image: manushreepb/skinglow-backend:latest
    container_name: gitoker-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - skinglow-network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    image: manushreepb/skinglow-frontend:latest
    container_name: gitoker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - skinglow-network
    environment:
      - REACT_APP_API_URL=http://localhost/api
      - HOST=0.0.0.0
    restart: always


networks:
  skinglow-network:
    driver: bridge
